---
name: Deploy

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions: {}

jobs:
  ci:
    permissions:
      actions: read
      contents: read
      packages: read
      security-events: write
    uses: einschmidt/workflows/.github/workflows/app-ci.yaml@6a57fef88f7f2a778a99121a5f66a2c840c0d47f # v0.1.2

  deploy:
    needs: ci
    permissions:
      contents: read
      packages: write
    uses: einschmidt/workflows/.github/workflows/app-deploy.yaml@6a57fef88f7f2a778a99121a5f66a2c840c0d47f # v0.1.2
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
