---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  workflows:
    uses: einschmidt/workflows/.github/workflows/labels.yaml@6a57fef88f7f2a778a99121a5f66a2c840c0d47f # v0.1.2
