---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: einschmidt/workflows/.github/workflows/pr-labels.yaml@6a57fef88f7f2a778a99121a5f66a2c840c0d47f # v0.1.2
